### ISSUE TITLE
Error on Death

### ISSUE THREAD

**Issue by marabb01** [Photon-GitHub/AACHider#1]
### Issue Description
Error
https://pastebin.com/mY9nWrWD

### Core Information
(_Do not just say "Latest"_)

**Server version**: 
1.8.8R0.1
**AAC version**: 
3.3.5
**AACadditionPro version**: 
3.4.2
**AAC-Hider version**: 
1.2.0
**ProtocolLib version**: 
4.2.1
**Plugin list**: (chat or actionbar plugins?)
https://prnt.sc/hkxqee
### Special Environment Info
**ViaVersion version**: insert version or say N/A
1.3.0
**ProtocolSupport version**: 
N
**ViaBackwards version**: 
N
**BungeeCord plugins**: (chat or actionbar plugins?)
N
### Configurations
Post your AAC-Hider config **and** AAC language.yml if altered. Or say "default" if untouched.
https://pastebin.com/TpHJEmxx

**Comment by Photon-GitHub** [comment]
Does this only happen after the execution of the suicide command?

**Comment by marabb01** [comment]
I used /suicide to make the error as noone else was online, it occurs when any player is killed.

**Comment by Photon-GitHub** [comment]
Addressed in 1.2.1
