### ISSUE TITLE
TabComplete /aac

### ISSUE THREAD

**Issue by FlamWy** [Photon-GitHub/AACHider#12]
I do not think that this is very important however you can tab to subcommands with /aac (https://prnt.sc/10a6j9i)
No, I am not OP'd or have any permission to do this.

### Core Information
**Server version**:  1.8.8 PaperSpigot

**AAC version**: 5.0.11

**AACadditionPro version**: 6.5.3

**AACPlus version**: 3.1.0

**ProtocolLib version**: 4.6.0

**Plugin list**: (chat or actionbar plugins?) not apart from chatcontrol and commandblocker (which shouldn't affect anything)

### Special Environment Info
**ViaVersion version**: 3.2.1

**ProtocolSupport version**: none

**ViaBackwards version**:  none

**BungeeCord plugins**: (chat or actionbar plugins?) none

### Configurations
default

AACPlus Config: 
Didn't include the banning part (DM if needed iFlamingoz#3731)
```
replacement: "Unknown command. Type \"/help\" for help."
commands: "{}"
exempt_admins: true
exempt_verbose: true
```

**Comment by Photon-GitHub** [comment]
Are you sure you have the current version of AACPlus? Your config is quite old, please let it regenerate.

**Comment by FlamWy** [comment]
Yes, here is the config that is being regenerated - https://pastebin.com/dgdTwBuF
