### ISSUE TITLE
Hide AACAddition Commands

### ISSUE THREAD

**Issue by marabb01** [Photon-GitHub/AACHider#2]
Core Information

(Do not just say "Latest")

Server version:
1.8.8R0.1
AAC version:
3.3.5
AACadditionPro version:
3.4.2
AAC-Hider version:
1.2.0
ProtocolLib version:
4.2.1
Plugin list: (chat or actionbar plugins?)
https://prnt.sc/hkxqee

Special Environment Info

ViaVersion version: insert version or say N/A
1.3.0
ProtocolSupport version:
N
ViaBackwards version:
N
BungeeCord plugins: (chat or actionbar plugins?)
N

Suggestion - I’d like to suggest that AACHider also doubles to block Addition commands. It’s a giveaway if hackers know to look for it, and ruins the effect of hiding AAC.

**Comment by Photon-GitHub** [comment]
#4 Recode should be done prior to that.

**Comment by Photon-GitHub** [comment]
Addressed in 1.3.0
