### ISSUE TITLE
Verbose command not hidden

### ISSUE THREAD

**Issue by marabb01** [Photon-GitHub/AACHider#3]
Core Information

(Do not just say "Latest")

Server version:
1.8.8R0.1
AAC version:
3.3.5
AACadditionPro version:
3.4.2
AAC-Hider version:
1.2.0
ProtocolLib version:
4.2.1
Plugin list: (chat or actionbar plugins?)
https://prnt.sc/hkxqee

Special Environment Info

ViaVersion version: insert version or say N/A
1.3.0
ProtocolSupport version:
N
ViaBackwards version:
N
BungeeCord plugins: (chat or actionbar plugins?)
N

Problem - Doing /aacverbose still shows the Permission command instead of being changed to the one set in the config.

**Comment by Photon-GitHub** [comment]
Addressed in 1.2.1
