### ISSUE TITLE
AACHider - /aacadmin - destroying message

### ISSUE THREAD

**Issue by 0xntpower** [Photon-GitHub/AACHider#5]
### Issue Description
Please include a detailed description of the issue, instructions to reproduce it and relevant error logs or screenshots/videos.
the problem is that when a player using the /aacadmin command with no OP and no permission then he will get this message "AAC / You do not have permissions to perform that command" and the problem with that message is that it actually telling the player that I am using AAC and that making AACHider not really useful can you please solve that? 

For large error pastes, please use https://hastebin.com/ (or similar)

### Core Information
(_Do not just say "Latest"_)

**Server version**: 1.8.8

**AAC version**: 3.3.7

**AACadditionPro version**: do not have the plugin yet 

**AAC-Hider version**: 1.3.0

**ProtocolLib version**: 4.3.0

**Plugin list**: AAC, AACHider, ConditionalCommands, ProtocolLib, ViaVersion-1.3.0, Vault, SaneEconomyCore-0.12.7-SNAPSHOT

### Special Environment Info
**ViaVersion version**: insert version or say N/A

**ProtocolSupport version**: 

**ViaBackwards version**: 

**BungeeCord plugins**: (chat or actionbar plugins?)

### Configurations
Post your AAC-Hider config **and** AAC language.yml if altered. Or say "default" if untouched.
default config for AACHider

**Comment by CeIebrimbor** [comment]
The default config has:
`block_aac_commands: false`

So if it is truly default, then you did not configure the plugin to your needs.

**Comment by 0xntpower** [comment]
ok i saw it now, thanks for the help!
