### ISSUE TITLE
AACAdditionPro command not hidden, Tab suggestions not hidden

### ISSUE THREAD

**Issue by Puremin0rez** [Photon-GitHub/AACHider#8]
### Issue Description
AACPlus does not appear to be hiding the AACAdditionPro command. It also does not hide the tab completion suggestions for both AAC and AACAdditionPlus.

### Core Information
**Server version**: Paper 1.15.1

**AAC version**: 4.3.4

**AACadditionPro version**: 6.0.1

**AACPlus version**: 2.1.1

**ProtocolLib version**: 4.5.0

**Plugin list**: AAC, AACAdditionPro, AACPlus, ConditionalCommands, ProtocolLib.

### Configurations
Entirely default configs (Optimized).

This image shows that /aac is hidden fine, but /aacadditionpro is not.
![image](https://user-images.githubusercontent.com/734478/71934986-4b21f600-316b-11ea-96ac-406e64133dee.png)

This image shows that the server is still suggesting me all of the various AAC commands.
![image](https://user-images.githubusercontent.com/734478/71935004-58d77b80-316b-11ea-9f62-35d3b4690846.png)

**Comment by Photon-GitHub** [comment]
Fixed in 2.2.0

**Comment by Keviro** [comment]
Still a thing in 2.2.0.

![H7asqxy](https://user-images.githubusercontent.com/25409956/72835979-037f8c00-3c8c-11ea-8096-d3b1b59a3ad0.png)

![Y6CUJTI](https://user-images.githubusercontent.com/25409956/72835929-eba80800-3c8b-11ea-82b9-5d756104406b.png)

Tab completion works for all AAC commands, not just for AACAdditionPro, but so it fits better on the screenshot ^^

**Comment by clrxbl** [comment]
Can confirm this still works on 2.2.0, would like to see this get fixed.
